phase2_start_service_processes() called -- currently a NOP
phase3_start_service_processes() called -- currently a NOP
phase4_start_service_processes() called -- currently a NOP
phase5_start_service_processes() called -- currently a NOP
testcase_main(): started
QUICK SUMMARY: Attempts (from multiple processes) to zap() a non-existent process.
testcase_main(): after fork of child 4
testcase_main(): after fork of child 5
testcase_main(): performing first join
XXp1(): started
XXp1(): arg = 'XXp1'
XXp1(): zapping a non existant processes pid, should fail.  Calling zap(204)
ERROR: Attempt to zap() a non-existent process.
TESTCASE ENDED: Call counts:   check_io() 0   clockHandler() 0
